# Generated by Django 5.0.14 on 2025-12-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_coin_circulating_supply_coin_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="price_change_percentage_1h",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="coin",
            name="price_change_percentage_7d",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
