# Generated by Django 5.0.14 on 2025-12-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin_id", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
