# Generated by Django 5.0.14 on 2025-12-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="holding",
            old_name="coin_id",
            new_name="asset_id",
        ),
        migrations.AddField(
            model_name="holding",
            name="asset_type",
            field=models.CharField(
                choices=[("crypto", "Cryptocurrency"), ("stock", "Stock")],
                default="crypto",
                max_length=10,
            ),
        ),
    ]
