# Generated by Django 5.0.14 on 2025-12-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_pricealert"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricealert",
            name="condition",
            field=models.CharField(
                choices=[("above", "Price Above"), ("below", "Price Below")],
                default="above",
                max_length=10,
            ),
        ),
    ]
